accounts/urls.py
from django.urls import path
from . import views
 
app_name = 'accounts'
urlpatterns = [
    path('register/',views.user_register, name='user_register'),
    path('login/',views.user_login, name='user_login'),
    path('logout/',views.user_logout, name='user_logout'),
    path('user-edit/', views.user_edit, name="user_edit"),
    path('profile/', views.user_profile, name='user_profile'),
    path('list-api/', views.list_api, name='list_api'),
    path('user-change-pass/', views.user_change_pass, name='user_change_pass'),
    #reset password
    path('reset/', views.UserPassReset.as_view(), name='reset_pass'),
	path('reset/done/', views.UserPassResetDone.as_view(), name='reset_pass_done'),
	path('reset/<uidb64>/<token>', views.UserPassResetConfirm.as_view(), name='reset_pass_confirm'),
	path('reset/complete/', views.UserPassResetComplete.as_view(), name='reset_pass_complete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
    path('',views.cart_detail, name='cart_detail'),  
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('secret :) /', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('odrers/', include('orders.urls', namespace='orders')),
    path('api/', include('doapi.urls', namespace='doapi')),
    path('api-token-auth/',obtain_auth_token, name='mytoken'),
    path('', include('doshop.urls', namespace='doshop')),

] 
# + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)  

doapi/urls.py
from django.urls import path
from . import views


app_name = 'doapi'
urlpatterns = [
    path('test-connect/',views.test_connect),
    path('test-post-get/',views.test_post_get),  
    path('all-categories/',views.categories), 
    path('all-companies/',views.companies), 
    path('special-price-products/',views.special_price_products), 
    path('category-products/<slug:slug>/',views.category_products),
    path('get-token/', views.get_token, name='get_token'),
    path('my-orders/', views.my_orders, name='my_orders'),

]

doshop/urls.py
from django.urls import path
from . import views

app_name = 'doshop'
urlpatterns = [  
    path('product/<slug:slug>/',views.product_detail, name='product-detail'),  
    path('category/<slug:slug>/',views.category_detail, name='category-detail'), 
    path('company/<slug:slug>/',views.company_detail, name='company-detail'), 
    path('special-price/',views.all_specialـprice, name='special-price'),
    path('page-not-found/',views.page_not_found, name='page_not_found'),
    #----- manager------------#
    path('insert-product/',views.insert_product, name='insert_product'),
    path('edit-product/<slug:slug>/',views.edit_product, name='edit_product'),
    path('edit-price-product/<slug:slug>/',views.edit_price_product, name='edit_price_product'),
    path('edit-available-product/<slug:slug>/',views.edit_available_product, name='edit_available_product'),
    path('not-available-products/',views.not_available_products, name='not_available_products'),
    path('all-order-list/',views.all_order_list, name='all_order_list'),
    #------End manager -------#
    path('',views.home, name='home'),
    
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/',views.order_create, name='order_create'), 
    path('order-detail/<int:order_id>/',views.order_detail, name='order_detail'), 
    path('order-delete/<int:order_id>/',views.order_delete, name='order_delete'), 
    path('orders-list/',views.order_list, name='order_list'), 
]

templates/lib/footer.html
 <!-- Footer-->
 <footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; sadegh.dev 2021</p></div>
</footer>

templates/lib/header.html
<!-- Header-->
<header class="bg-warning shadow py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder ">Miner Shop</h1>
            <p class="lead fw-normal text-white-80 mb-0 ">فروشگاه آنلاین </p>
        </div>
    </div>
</header>

templates/lib/header_accounts.html
<!-- Header-->
<header class="bg-success shadow py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder ">Profile</h1>
            <p class="lead fw-normal text-white-80 mb-0 ">پروفایل کاربری</p>
        </div>
    </div>
</header>

templates/lib/header_social.html
<!-- Header-->
<header class="bg-info shadow  py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Social Network</h1>
            <p class="lead fw-normal text-white-80 mb-0">شبکه اجتماعی</p>
        </div>
    </div>
</header>

templates/lib/messages.html
{% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }}" role="alert"  >
            {{ msg }}  
        </div>
    {% endfor %}
{% endif %}

templates/lib/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="{% url 'doshop:home' %}"> BTCR.sadegh.dev </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
            <li class="nav-item"><a class="nav-link active" href="{% url 'posts:all_posts' %}"> شبکه اجتماعی</a></li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">انواع محصولات</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for ct in categories %}
                    <li><a class="dropdown-item" href="{{ ct.get_absolute_url }}">{{ ct.name }}</a></li>
                  {% endfor %}
                </ul>
              </li> 
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">شرکت های سازنده</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for co in companies %}
                    <li><a class="dropdown-item" href="{{ co.get_absolute_url }}">{{ co.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
              <li class="nav-item"><a class="nav-link rounded bg-danger text-white active" href="{% url 'doshop:special-price' %}"> فروش ویژه </a></li>
          </ul>
          {% if user.is_authenticated %}
              <div class="btn bg-secondary mx-1"><a class="text-white me-1" style='text-decoration:none' href="{% url 'cart:cart_detail' %}">
                <i class="bi-cart-fill me-1"></i>
                      سبد خرید
              </a></div>
              <div class="btn mx-1"><a class="text-dark me-1" style='text-decoration:none' href="{% url 'accounts:user_profile' %}">پروفایل کاربری</a></div>
              <div class="btn mx-1"><a class="text-dark me-1" style='text-decoration:none' href="{% url 'accounts:user_logout' %}">خروج</a></div>
          {% else %}
                <div class="btn mx-1"><a class="text-dark me-1" style='text-decoration:none' href="{% url 'accounts:user_register' %}">ایجاد حساب کاربری</a></div>
                <div class="btn mx-1"><a class="text-dark me-1" style='text-decoration:none' href="{% url 'accounts:user_login' %}">ورود</a></div>
          {% endif %}
          
      </div>
  </div>
</nav> 

templates/lib/navbar_accounts.html
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="{% url 'doshop:home' %}"> BTCR.sadegh.dev </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            {% if user.access_level == 'o' %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light bg-success rounded" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  پنل مدیریت
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'doshop:insert_product' %}">ثبت کالای جدید</a></li>
                  <li><a class="dropdown-item" href="{% url 'doshop:not_available_products' %}">لیست کالاهای غیرفعال</a></li>
                  <li><a class="dropdown-item" href="{% url 'doshop:all_order_list' %}">لیست سفارشات کاربران</a></li>
                  <li><a class="dropdown-item" href="{% url 'doshop:all_order_list' %}"></a></li>
                </ul>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'accounts:user_profile' %}">پروفایل</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'accounts:user_change_pass' %}">تغییر رمز عبور</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'doapi:get_token' %}">دریافت توکن api</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'accounts:list_api' %}">api های کاربردی</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'accounts:user_edit' %}">ویرایش مشخصات</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'orders:order_list' %}">سفارشات ثبت شده</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'doshop:home' %}">بازگشت</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'accounts:user_logout' %}">خروج</a>
              </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'accounts:user_register' %}">ثبت نام</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'accounts:user_login' %}"> ورود</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

templates/lib/navbar_social.html
<!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="{% url 'doshop:home' %}"> BTCR.sadegh.dev </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'posts:all_posts' %}">صفحه اصلی شبکه اجتماعی</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">دسته بندی مطالب</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for ct in categories %}
                        <li><a class="dropdown-item" href="{{ ct.get_absolute_url }}">{{ ct.name }}</a></li>
                    {% endfor %}
                </ul>
            </li> 
            {% if request.user.id %}
                <li class="nav-item">
                  <a class="nav-link text-dark" href="{% url 'posts:add_post' %}">نوشتن مطلب جدید</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-dark" href="{% url 'posts:dashboard' request.user.id %}">نوشته های من</a>
                </li>
                    <li class="nav-item">
                  <a class="nav-link text-dark" href="{% url 'accounts:user_profile' %}">پروفایل کاربری</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'accounts:user_logout' %}">خروج</a>
                </li>
          {% else %}
            
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'accounts:user_register' %}">ثبت نام</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'accounts:user_login' %}"> ورود</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>




 