accounts/urls.py
from django.urls import path
from . import views
 
app_name = 'accounts'
urlpatterns = [
    path('register/',views.user_register, name='user_register'),
    path('login/',views.user_login, name='user_login'),
    path('logout/',views.user_logout, name='user_logout'),
    path('user-edit/', views.user_edit, name="user_edit"),
    path('profile/', views.user_profile, name='user_profile'),
    path('list-api/', views.list_api, name='list_api'),
    path('user-change-pass/', views.user_change_pass, name='user_change_pass'),
    #reset password
    path('reset/', views.UserPassReset.as_view(), name='reset_pass'),
	path('reset/done/', views.UserPassResetDone.as_view(), name='reset_pass_done'),
	path('reset/<uidb64>/<token>', views.UserPassResetConfirm.as_view(), name='reset_pass_confirm'),
	path('reset/complete/', views.UserPassResetComplete.as_view(), name='reset_pass_complete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
    path('',views.cart_detail, name='cart_detail'),  
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('secret :) /', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('odrers/', include('orders.urls', namespace='orders')),
    path('api/', include('doapi.urls', namespace='doapi')),
    path('api-token-auth/',obtain_auth_token, name='mytoken'),
    path('', include('doshop.urls', namespace='doshop')),

] 
# + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)  

doshop/urls.py
from django.urls import path
from . import views

app_name = 'doshop'
urlpatterns = [  
    path('product/<slug:slug>/',views.product_detail, name='product-detail'),  
    path('category/<slug:slug>/',views.category_detail, name='category-detail'), 
    path('company/<slug:slug>/',views.company_detail, name='company-detail'), 
    path('special-price/',views.all_specialـprice, name='special-price'),
    path('page-not-found/',views.page_not_found, name='page_not_found'),
    #----- manager------------#
    path('insert-product/',views.insert_product, name='insert_product'),
    path('edit-product/<slug:slug>/',views.edit_product, name='edit_product'),
    path('edit-price-product/<slug:slug>/',views.edit_price_product, name='edit_price_product'),
    path('edit-available-product/<slug:slug>/',views.edit_available_product, name='edit_available_product'),
    path('not-available-products/',views.not_available_products, name='not_available_products'),
    path('all-order-list/',views.all_order_list, name='all_order_list'),
    #------End manager -------#
    path('',views.home, name='home'),
    
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/',views.order_create, name='order_create'), 
    path('order-detail/<int:order_id>/',views.order_detail, name='order_detail'), 
    path('order-delete/<int:order_id>/',views.order_delete, name='order_delete'), 
    path('orders-list/',views.order_list, name='order_list'), 
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .managers import MyUserManager

 
class User(AbstractBaseUser):
    ''' class of Custom User'''
    email =         models.EmailField(max_length=254, unique=True)
    #password

    full_name =     models.CharField(max_length=200)
    national_code = models.CharField(max_length=10, unique=True) #validate
    image =         models.ImageField(upload_to='profile/%Y/%m/%d/', default='profile/default.jpg')
    
    mobile =        models.CharField(max_length=11, unique=True) #validate
    address =       models.TextField()
    
    ACCESS_LEVELS = (
        ('s','simple'),
        ('o','operator')
    )
    access_level =  models.CharField(max_length=1,  choices=ACCESS_LEVELS, default = 's')
    
    is_admin =      models.BooleanField(default=False)
    is_active =     models.BooleanField(default=True)
    
    created =       models.DateTimeField(auto_now_add=True)
    updated =       models.DateTimeField(auto_now=True)
    #book =         models.ForeignKey(Book, on_delete=models.SET_NULL) OR models.PositiveIntegerField(idBook or 0)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name', 'national_code', 'mobile', 'address','image']
    objects = MyUserManager()

    def __str__(self):
        return f'{self.full_name} - {self.email} - {self.access_level}'

    def has_perm(self, perm, obj=None):
        return True
    
    def has_module_perms(self, app_lable):
        return True

    @property
    def is_staff(self):
        return self.is_admin

accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import UserLoginForm, UserRegisterForm, UserChangeForm, UserChangePassForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import User
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

#reCaptcha
import urllib
import json
from core import settings

def user_register(request):
    ''' User register function

    use captcha 
    '''
    if request.method == 'POST' :
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            ## CAPTCHA ##########################
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response' : recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req =  urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            ## CAPTCHA ######################
            if result['success']:
                cd = form.cleaned_data
                user = User.objects.create_user( cd['email'], cd['password1'], cd['image'] ,cd['full_name'], cd['national_code'], cd['mobile'], cd['address'] )
                user.save()
                login(request, user)
                messages.success(request,'ثبت نام با موفقیت انجام شد','success')
                return redirect('doshop:home')         
            else:
                messages.error(request,'لطفا گزینه من ربات نیستم را ثبت نمایید','danger')
    else :
        form = UserRegisterForm()
    context = {
        'form' : form
    }
    return render(request,'accounts/register.html',context)

"""
def user_register(request):
    if request.method == 'POST' :
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user( cd['email'], cd['password1'], cd['full_name'], cd['national_code'], cd['mobile'], cd['address'] )
            user.save()
            login(request, user)
            messages.success(request,'ثبت نام با موفقیت انجام شد','success')
            return redirect('doshop:home')
    else :
        form = UserRegisterForm()
    context = {
        'form' : form
    }
    return render(request,'accounts/register.html',context)

"""

def user_login(request):
    next = request.GET.get('next')
    if request.method == 'POST' :
        form = UserLoginForm(request.POST)
        if form.is_valid():
            ## CAPTCHA ##########################
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response' : recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req =  urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            ## CAPTCHA ######################
            if result['success']:
                cd = form.cleaned_data
                user = authenticate(request, email=cd['email'], password=cd['password'])
                if user is not None :
                    login(request, user)
                    messages.success(request,'ورود با موفقیت انجام شد','success')
                    if next :
                        return redirect(next)
                    return redirect('doshop:home')
                else :
                    messages.success(request,'ایمیل یا رمز عبور صحیح نمی باشد','danger')
            else:
                messages.error(request,'لطفا گزینه من ربات نیستم را ثبت نمایید','danger')
    else :
        form = UserLoginForm()
    context = {
        'form' : form
    }
    return render (request,'accounts/login.html',context)

"""
def user_login(request):
    next = request.GET.get('next')
    if request.method == 'POST' :
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, email=cd['email'], password=cd['password'])
            if user is not None :
                login(request, user)
                messages.success(request,'ورود با موفقیت انجام شد','success')
                if next :
                    return redirect(next)
                return redirect('doshop:home')
            else :
                messages.success(request,'ایمیل یا رمز عبور صحیح نمی باشد','danger')
    else :
        form = UserLoginForm()
    context = {
        'form' : form
    }
    return render (request,'accounts/login.html',context)
"""

@login_required
def user_logout(request):
    logout(request)
    messages.success(request,'شما با موفقیت از سیستم خارج شدید','success')
    return redirect('doshop:home')



@login_required
def user_edit(request):
    myid = request.user.id
    me = get_object_or_404(User, id = myid)
    if request.method =='POST':
        form = UserChangeForm(request.POST, request.FILES, instance=me)
        if form.is_valid():
            form.save()
            messages.success(request,'ویرایش مشخصات با موفقیت انجام شد','success')
            return redirect('accounts:user_profile')
    else :
        form = UserChangeForm(instance=me)
    context = {
        'form' : form
    }
    return render (request,'accounts/user_edit.html',context)



@login_required
def user_profile(request):
    user_id = request.user.id
    the_user = get_object_or_404(User, id = user_id)
    context = {
        'the_user' : the_user
    }
    return render(request,'accounts/user_profile.html', context)

    


@login_required
def user_change_pass(request):
    user_id = request.user.id
    the_user = get_object_or_404(User, id = user_id)
    if request.method == 'POST' :
        form = UserChangePassForm(request.POST, instance=the_user)
        if form.is_valid():
            ## CAPTCHA ##########################
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response' : recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req =  urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            ## CAPTCHA ######################
            if result['success']:
                cp = form.cleaned_data['current_password']
                em = request.user.email
                user = authenticate(request, email=em, password=cp)
                if user is not None :
                    fm = form.save(commit=False)
                    fm.password1 = form.cleaned_data['password1']
                    fm.save()
                    login(request,the_user)
                    messages.success(request, 'رمز عبور با موفقیت تغییر کرد', 'success')
                    return redirect('accounts:user_profile')
                else :
                    messages.error(request,'رمز عبور فعلی خود را اشتباه وارد کرده اید','danger')
            else:
                messages.error(request,'لطفا گزینه من ربات نیستم را ثبت نمایید','danger')
    else:
        form = UserChangePassForm(instance = the_user)
    context = {'form': form}
    return render(request,'accounts/user_change_pass.html', context)


"""
@login_required
def user_change_pass(request):
    user_id = request.user.id
    the_user = get_object_or_404(User, id = user_id)
    if request.method == 'POST' :
        form = UserChangePassForm(request.POST, instance=the_user)
        if form.is_valid():
            ## CAPTCHA ##########################
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response' : recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req =  urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            ## CAPTCHA ######################
            if result['success']:
                fm = form.save(commit=False)
                fm.password1 = form.cleaned_data['password1']
                fm.save()
                login(request,the_user)
                messages.success(request, 'رمز عبور با موفقیت تغییر کرد', 'success')
                return redirect('accounts:user_profile')
            else:
                messages.error(request,'لطفا گزینه من ربات نیستم را ثبت نمایید','danger')
    else:
        form = UserChangePassForm(instance = the_user)
    context = {'form': form}
    return render(request,'accounts/user_change_pass.html', context)

"""

def list_api(request):
    return render(request,'accounts/list_api.html')




# ------------------------------------ #
# Reset Password # Forget Password

class UserPassReset(auth_views.PasswordResetView):
    template_name = 'accounts/password/password_reset_form.html'
    success_url = reverse_lazy('accounts:reset_pass_done')
    email_template_name = 'accounts/password/password_reset_email.html'


class UserPassResetDone(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password/password_reset_done.html'


class UserPassResetConfirm(auth_views.PasswordResetConfirmView):

templates/accounts/manager/all_order_list.html
{% extends 'base_accounts.html' %}

{% block title %}  {% endblock %}
{% block content %}   
    <!-- order obj -->
    <!--#####################-->
    <table dir='rtl' class="table table-striped ">
        <thead class="bg-secondary text-white">
        <tr>
            <th scope="col">ردیف</th>
            <th scope="col" class="text-center">کاربر سفارش دهنده</th>
            <th scope="col" class="text-center">شماره تماس کاربر</th>
            <th scope="col" class="text-center">مبلغ سفارش</th>
            <th scope="col" class="text-center">تاریخ ثبت سفارش</th>
            <th scope="col" class="text-center">وضعیت پرداخت</th>
            <th scope="col" class="text-center"> جزئیات</th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <!-- item has info of sessions not model -->
                <td class="text-center">{{ order.user.full_name }}</td>
                <td class="text-center">{{ order.user.mobile }}</td>
                <td class="text-center">{{ order.total_price|floatformat:"-3g"  }} تومان</td>
                <td class="text-center">{{ order.created }}</td>
                <td class="text-center">
                    {% if order.paid %}
                        <a type="button" class="btn btn-success w-100 d-inline-block">پرداخت شده است</a>
                    {% else %}
                        <a type="button" class="btn btn-warning w-100 d-inline-block">عدم پرداخت</a>
                    {% endif %}
                </td>
                <td class="text-center" ><a href="{% url 'orders:order_detail' order.id %} " type="button" class="btn btn-info w-100 d-inline-block">جزئیات</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="w-100" dir='ltr'>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center ">
                {% if orders.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item"><a class="page-link" href="?page={{ orders.previous_page_number }}" >{{ orders.previous_page_number }}</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link bg-secondary text-light " >{{ orders.number }}</a></li>
                {% if orders.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ orders.next_page_number }}" >{{ orders.next_page_number }}</a></li>
                    <li class="page-item">
                            <a class="page-link" href="?page={{ orders.paginator.num_pages }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>

{% endblock %} 

templates/accounts/manager/edit_available_product.html
{% extends 'base_accounts.html' %}
{% load thumbnail %}
{% block title %} تغییر قیمت کالا {% endblock %}
{% block content %}
    <!-- Section-->
    <div class="col mb-5 w-50 p-3">
        <div class="card h-100">
            <!-- Sale badge-->
            {% if product.specialـprice %}
                <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">فروش ویژه</div>
            {% endif %}
                <!-- Product image-->
            {% thumbnail product.image "500x500" as img %}
            <a href='{{ product.get_absolute_url }}'><img class="card-img-top" src="{{ img.url }}" alt="{{ img.name }}" /></a>
            {% endthumbnail %}
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center" dir=rtl>
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{ product.name }}</h5>
                </div>
                <h4>تغییر وضعیت کالا</h4>
            <form action='' method="POST" >
                {% csrf_token %}
                {{ form.as_p }}
                <input type='submit' class='btn btn-primary' value='تغییر وضعیت'>
                <a href="{% url 'doshop:home' %}" type="button" class="btn btn-danger">انصراف</a>
            </form>
            </div>           
        </div>
    </div>
{% endblock %}

templates/accounts/manager/edit_price_product.html
{% extends 'base_accounts.html' %}
{% load thumbnail %}
{% block title %} تغییر قیمت کالا {% endblock %}
{% block content %}
    <!-- Section-->
    <div class="col mb-5 w-50 p-3">
        <div class="card h-100">
            <!-- Sale badge-->
            {% if product.specialـprice %}
                <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">فروش ویژه</div>
            {% endif %}
                <!-- Product image-->
            {% thumbnail product.image "500x500" as img %}
            <a href='{{ product.get_absolute_url }}'><img class="card-img-top" src="{{ img.url }}" alt="{{ img.name }}" /></a>
            {% endthumbnail %}
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center" dir=rtl>
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{ product.name }}</h5>
                </div>
                <h4>تغییر قیمت کالا</h4>
            <form action='' method="POST" >
                {% csrf_token %}
                {{ form.as_p }}
                <input type='submit' class='btn btn-primary' value='ثبت قیمت جدید'>
                <a href="{% url 'doshop:home' %}" type="button" class="btn btn-danger">انصراف</a>
            </form>
            </div>           
        </div>
    </div>
{% endblock %}

templates/accounts/manager/edit_product.html
{% extends 'base_accounts.html' %}
{% block title %} ویرایش مشخصات کالا {% endblock %}
{% block content %}
    <h4>ویرایش مشخصات کالا </h4>
    <form enctype="multipart/form-data" action='' method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class='btn btn-primary' value='ثبت ویرایش'>
        <a href="{% url 'doshop:home' %}" type="button" class="btn btn-danger">انصراف</a>
    </form>
{% endblock %}

templates/accounts/manager/insert_product.html
{% extends 'base_accounts.html' %}
{% block title %} ثبت کالای جدید {% endblock %}
{% block content %}
    <h4> ثبت کالای جدید </h4>
    <form enctype="multipart/form-data" action='' method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class='btn btn-primary' value='ثبت کالا'>
        <a href="{% url 'doshop:home' %}" type="button" class="btn btn-danger">انصراف</a>
    </form>
{% endblock %}

templates/accounts/manager/not_available_products.html
{% extends 'base_accounts.html' %}
{% load thumbnail %}

{% block title %} فروشگاه آنلاین {% endblock %}
{% block content %}   
    <!-- Section-->
    {% for product in products %}
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Sale badge-->
                {% if product.specialـprice %}
                    <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">فروش ویژه</div>
                {% endif %}
                    <!-- Product image-->
                {% thumbnail product.image "300x300" as img %}
                <img class="card-img-top" src="{{ img.url }}" alt="{{ img.name }}" />
                {% endthumbnail %}
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center" dir='rtl'>
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{ product.name }}</h5>
                        <!-- Product price-->
                        {% if product.specialـprice %}
                            <span class="text-muted text-decoration-line-through">{{ product.price|floatformat:"-3g" }}</span>
                            <span class="text-danger ">{{ product.specialـprice|floatformat:"-3g" }} </span>  تومان
                        {% else %}
                            {{ product.price|floatformat:"-3g"  }}تومان
                        {% endif %}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a href='{% url "doshop:edit_available_product" product.slug %}' class="btn btn-outline-dark mt-auto">فعال کردن کالا</a></div>
                </div>
            </div>
        </div>
    {% empty %}
        <h5 dir='rtl' class="fw-bolder">موردی یافت نشد</h5>
    {% endfor %}
{% endblock %}